const mockWeatherData = [
// 🌦️ LONDON
{
city: { name: "London", country: "Great Britain" },
current: {
    temperature: 18,
    condition: "Cloudy",
    icon: "cloud",
    feels_like: 17,
    humidity: 65,
    wind_speed: 10,
    precipitation: 0,
    visibility: 8,
    sunrise: "06:20",
    sunset: "18:45",
},

// ✅ Hourly forecast organized per day (Monday–Sunday)
hourly: {
    Monday: [
    { time: "06:00", temperature: 13, condition: "Rainy", icon: "rain" },
    { time: "09:00", temperature: 15, condition: "Cloudy", icon: "cloud" },
    { time: "12:00", temperature: 18, condition: "Light Rain", icon: "rain" },
    { time: "15:00", temperature: 20, condition: "Rainy", icon: "rain" },
    { time: "18:00", temperature: 17, condition: "Overcast", icon: "cloud" },
    { time: "21:00", temperature: 15, condition: "Drizzle", icon: "rain" },
    { time: "00:00", temperature: 13, condition: "Foggy", icon: "fog" },
    { time: "03:00", temperature: 12, condition: "Foggy", icon: "fog" },
    ],
    Tuesday: [
    { time: "06:00", temperature: 12, condition: "Cloudy", icon: "cloud" },
    { time: "09:00", temperature: 15, condition: "Partly Cloudy", icon: "cloud-sun" },
    { time: "12:00", temperature: 18, condition: "Sunny", icon: "sun" },
    { time: "15:00", temperature: 21, condition: "Sunny", icon: "sun" },
    { time: "18:00", temperature: 17, condition: "Cloudy", icon: "cloud" },
    { time: "21:00", temperature: 14, condition: "Cloudy Night", icon: "storm" },
    { time: "00:00", temperature: 13, condition: "Clear Night", icon: "snow" },
    { time: "03:00", temperature: 12, condition: "Foggy", icon: "fog" },
    ],
    Wednesday: [
    { time: "06:00", temperature: 14, condition: "Sunny", icon: "sun" },
    { time: "09:00", temperature: 17, condition: "Sunny", icon: "sun" },
    { time: "12:00", temperature: 21, condition: "Clear Sky", icon: "sun" },
    { time: "15:00", temperature: 23, condition: "Clear Sky", icon: "sun" },
    { time: "18:00", temperature: 19, condition: "Partly Cloudy", icon: "cloud-sun" },
    { time: "21:00", temperature: 16, condition: "Clear Night", icon: "snow" },
    { time: "00:00", temperature: 14, condition: "Clear Night", icon: "storm" },
    { time: "03:00", temperature: 13, condition: "Foggy", icon: "fog" },
    ],
    Thursday: [
    { time: "06:00", temperature: 13, condition: "Partly Cloudy", icon: "cloud-sun" },
    { time: "09:00", temperature: 16, condition: "Sunny", icon: "sun" },
    { time: "12:00", temperature: 19, condition: "Sunny", icon: "sun" },
    { time: "15:00", temperature: 22, condition: "Partly Cloudy", icon: "cloud-sun" },
    { time: "18:00", temperature: 18, condition: "Cloudy", icon: "cloud" },
    { time: "21:00", temperature: 15, condition: "Cloudy Night", icon: "cloud" },
    { time: "00:00", temperature: 13, condition: "Foggy", icon: "fog" },
    { time: "03:00", temperature: 12, condition: "Foggy", icon: "fog" },
    ],
    Friday: [
    { time: "06:00", temperature: 11, condition: "Rain Showers", icon: "rain" },
    { time: "09:00", temperature: 13, condition: "Thunderstorm", icon: "storm" },
    { time: "12:00", temperature: 17, condition: "Thunderstorm", icon: "storm" },
    { time: "15:00", temperature: 19, condition: "Rainy", icon: "rain" },
    { time: "18:00", temperature: 16, condition: "Overcast", icon: "cloud" },
    { time: "21:00", temperature: 13, condition: "Drizzle", icon: "rain" },
    { time: "00:00", temperature: 12, condition: "Foggy", icon: "fog" },
    { time: "03:00", temperature: 11, condition: "Foggy", icon: "fog" },
    ],
    Saturday: [
    { time: "06:00", temperature: 10, condition: "Foggy", icon: "fog" },
    { time: "09:00", temperature: 13, condition: "Cloudy", icon: "cloud" },
    { time: "12:00", temperature: 16, condition: "Partly Cloudy", icon: "cloud-sun" },
    { time: "15:00", temperature: 18, condition: "Cloudy", icon: "cloud" },
    { time: "18:00", temperature: 15, condition: "Foggy", icon: "fog" },
    { time: "21:00", temperature: 12, condition: "Foggy", icon: "fog" },
    { time: "00:00", temperature: 11, condition: "Foggy", icon: "fog" },
    { time: "03:00", temperature: 10, condition: "Foggy", icon: "fog" },
    ],
    Sunday: [
    { time: "06:00", temperature: 9, condition: "Snow Showers", icon: "snow" },
    { time: "09:00", temperature: 10, condition: "Light Snow", icon: "snow" },
    { time: "12:00", temperature: 13, condition: "Cloudy", icon: "cloud" },
    { time: "15:00", temperature: 15, condition: "Snow Showers", icon: "snow" },
    { time: "18:00", temperature: 12, condition: "Cloudy", icon: "cloud" },
    { time: "21:00", temperature: 10, condition: "Snow Showers", icon: "snow" },
    { time: "00:00", temperature: 9, condition: "Foggy", icon: "fog" },
    { time: "03:00", temperature: 8, condition: "Foggy", icon: "fog" },
    ],
},

daily: [
    { day: "Monday", temperature: { min: 12, max: 20 }, condition: "Rainy", icon: "rain" },
    { day: "Tuesday", temperature: { min: 13, max: 21 }, condition: "Cloudy", icon: "cloud" },
    { day: "Wednesday", temperature: { min: 15, max: 23 }, condition: "Sunny", icon: "sun" },
    { day: "Thursday", temperature: { min: 14, max: 22 }, condition: "Partly Cloudy", icon: "cloud-sun" },
    { day: "Friday", temperature: { min: 12, max: 19 }, condition: "Thunderstorm", icon: "storm" },
    { day: "Saturday", temperature: { min: 11, max: 18 }, condition: "Foggy", icon: "fog" },
    { day: "Sunday", temperature: { min: 10, max: 17 }, condition: "Snow Showers", icon: "snow" },
],
},


// 🗽 NEW YORK
{
    city: { name: "New York", country: "United States" },
    current: {
    temperature: 25,
    condition: "Sunny",
    icon: "sun",
    feels_like: 27,
    humidity: 50,
    wind_speed: 12,
    precipitation: 5,
    visibility: 10,
    sunrise: "06:10",
    sunset: "19:15",
    },
    hourly: [
    { time: "06:00", temperature: 20, condition: "Clear", icon: "sun" },
    { time: "09:00", temperature: 23, condition: "Sunny", icon: "sun" },
    { time: "12:00", temperature: 27, condition: "Sunny", icon: "sun" },
    { time: "15:00", temperature: 28, condition: "Partly Cloudy", icon: "cloud-sun" },
    { time: "18:00", temperature: 25, condition: "Rain Showers", icon: "rain" },
    { time: "21:00", temperature: 22, condition: "Clear Night", icon: "moon" },
    { time: "00:00", temperature: 21, condition: "Clear Night", icon: "moon" },
    { time: "03:00", temperature: 19, condition: "Foggy", icon: "fog" },
    ],
    daily: [
    { day: "Monday", temperature: { min: 18, max: 29 }, condition: "Sunny", icon: "sun" },
    { day: "Tuesday", temperature: { min: 20, max: 30 }, condition: "Sunny", icon: "sun" },
    { day: "Wednesday", temperature: { min: 21, max: 32 }, condition: "Sunny", icon: "sun" },
    { day: "Thursday", temperature: { min: 19, max: 28 }, condition: "Partly Cloudy", icon: "cloud-sun" },
    { day: "Friday", temperature: { min: 18, max: 27 }, condition: "Rainy", icon: "rain" },
    { day: "Saturday", temperature: { min: 17, max: 26 }, condition: "Thunderstorm", icon: "storm" },
    { day: "Sunday", temperature: { min: 16, max: 25 }, condition: "Cloudy", icon: "cloud" },
    ],
},

// 🏯 TOKYO
{
    city: { name: "Tokyo", country: "Japan" },
    current: {
    temperature: 30,
    condition: "Humid",
    icon: "cloud-sun",
    feels_like: 33,
    humidity: 75,
    wind_speed: 8,
    precipitation: 10,
    visibility: 7,
    sunrise: "05:30",
    sunset: "18:40",
    },
    hourly: [
    { time: "06:00", temperature: 26, condition: "Humid", icon: "cloud-sun" },
    { time: "09:00", temperature: 28, condition: "Sunny", icon: "sun" },
    { time: "12:00", temperature: 31, condition: "Hot", icon: "sun" },
    { time: "15:00", temperature: 32, condition: "Humid", icon: "cloud-sun" },
    { time: "18:00", temperature: 29, condition: "Rain Showers", icon: "rain" },
    { time: "21:00", temperature: 27, condition: "Cloudy", icon: "cloud" },
    { time: "00:00", temperature: 25, condition: "Cloudy Night", icon: "cloud-moon" },
    { time: "03:00", temperature: 24, condition: "Foggy", icon: "fog" },
    ],
    daily: [
    { day: "Monday", temperature: { min: 24, max: 32 }, condition: "Rainy", icon: "rain" },
    { day: "Tuesday", temperature: { min: 23, max: 31 }, condition: "Sunny", icon: "sun" },
    { day: "Wednesday", temperature: { min: 25, max: 33 }, condition: "Humid", icon: "cloud-sun" },
    { day: "Thursday", temperature: { min: 22, max: 30 }, condition: "Thunderstorm", icon: "storm" },
    { day: "Friday", temperature: { min: 21, max: 29 }, condition: "Cloudy", icon: "cloud" },
    { day: "Saturday", temperature: { min: 20, max: 28 }, condition: "Foggy", icon: "fog" },
    { day: "Sunday", temperature: { min: 19, max: 27 }, condition: "Snow Showers", icon: "snow" },
    ],
},

// 🌧️ LAGOS
{
    city: { name: "Lagos", country: "Nigeria" },
    current: {
    temperature: 29,
    condition: "Rainy",
    icon: "rain",
    feels_like: 32,
    humidity: 85,
    wind_speed: 15,
    precipitation: 15,
    visibility: 6,
    sunrise: "06:30",
    sunset: "18:55",
    },
    hourly: [
    { time: "06:00", temperature: 26, condition: "Rainy", icon: "rain" },
    { time: "09:00", temperature: 28, condition: "Cloudy", icon: "cloud" },
    { time: "12:00", temperature: 30, condition: "Sunny", icon: "sun" },
    { time: "15:00", temperature: 31, condition: "Thunderstorm", icon: "storm" },
    { time: "18:00", temperature: 28, condition: "Rain Showers", icon: "rain" },
    { time: "21:00", temperature: 26, condition: "Cloudy Night", icon: "cloud-moon" },
    { time: "00:00", temperature: 25, condition: "Rainy", icon: "rain" },
    { time: "03:00", temperature: 24, condition: "Foggy", icon: "fog" },
    ],
    daily: [
    { day: "Monday", temperature: { min: 25, max: 32 }, condition: "Rainy", icon: "rain" },
    { day: "Tuesday", temperature: { min: 26, max: 33 }, condition: "Cloudy", icon: "cloud" },
    { day: "Wednesday", temperature: { min: 27, max: 34 }, condition: "Thunderstorm", icon: "storm" },
    { day: "Thursday", temperature: { min: 25, max: 31 }, condition: "Sunny", icon: "sun" },
    { day: "Friday", temperature: { min: 24, max: 30 }, condition: "Sunny", icon: "sun" },
    { day: "Saturday", temperature: { min: 23, max: 29 }, condition: "Rainy", icon: "rain" },
    { day: "Sunday", temperature: { min: 22, max: 28 }, condition: "Foggy", icon: "fog" },
    ],
},
];

export default mockWeatherData;
